"""Audio formats and bounds owned by the active Voice Agent v2 path."""

from __future__ import annotations

from .contracts import AudioFormat

INPUT_AUDIO_FORMAT = AudioFormat(
    encoding="pcm_s16le", sample_rate_hz=16_000, channels=1, sample_width_bytes=2
)
TTS_OUTPUT_AUDIO_FORMAT = AudioFormat(
    encoding="pcm_s16le", sample_rate_hz=48_000, channels=1, sample_width_bytes=2
)
INPUT_MEDIA_MAX_SECONDS = 30
INPUT_MEDIA_MAX_SAMPLES = INPUT_AUDIO_FORMAT.sample_rate_hz * INPUT_MEDIA_MAX_SECONDS
INPUT_MEDIA_MAX_BYTES = INPUT_MEDIA_MAX_SAMPLES * INPUT_AUDIO_FORMAT.sample_width_bytes
TTS_V2_OUTPUT_MEDIA_MAX_SECONDS = 180
TTS_V2_OUTPUT_MEDIA_MAX_SAMPLES = (
    TTS_OUTPUT_AUDIO_FORMAT.sample_rate_hz * TTS_V2_OUTPUT_MEDIA_MAX_SECONDS
)
TTS_V2_OUTPUT_MEDIA_MAX_BYTES = (
    TTS_V2_OUTPUT_MEDIA_MAX_SAMPLES * TTS_OUTPUT_AUDIO_FORMAT.sample_width_bytes
)
TTS_SEGMENT_MAX_SECONDS = 15
TTS_SEGMENT_MAX_SAMPLES = TTS_OUTPUT_AUDIO_FORMAT.sample_rate_hz * TTS_SEGMENT_MAX_SECONDS
TTS_SEGMENT_MAX_BYTES = TTS_SEGMENT_MAX_SAMPLES * TTS_OUTPUT_AUDIO_FORMAT.sample_width_bytes
OUTPUT_FRAME_MS = 20
OUTPUT_FRAME_SAMPLES = TTS_OUTPUT_AUDIO_FORMAT.sample_rate_hz * OUTPUT_FRAME_MS // 1_000
OUTPUT_FRAME_BYTES = OUTPUT_FRAME_SAMPLES * TTS_OUTPUT_AUDIO_FORMAT.sample_width_bytes
OUTPUT_DELIVERY_BLOCK_MS = 60
OUTPUT_DELIVERY_BLOCK_SAMPLES = (
    TTS_OUTPUT_AUDIO_FORMAT.sample_rate_hz * OUTPUT_DELIVERY_BLOCK_MS // 1_000
)
OUTPUT_DELIVERY_BLOCK_BYTES = (
    OUTPUT_DELIVERY_BLOCK_SAMPLES * TTS_OUTPUT_AUDIO_FORMAT.sample_width_bytes
)
